---
- name: Install and configure Hashicorp Consul
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  tags: [install]

  roles:
    - name: Uninstall Consul
      role: ansible-role-consul-uninstall
    - name: Install consul
      role: ansible-role-consul-install
    - name: Configure files in all nodes
      role: ansible-role-consul-configure

# - name: Configure all consul hosts
#   hosts: all
#   become: yes
#   become_user: root
#   gather_facts: yes
#   tags: [consul]

#   roles:
#     - name: Configure all consul hosts
#       role: ansible-role-consul-hosts-conf

- name: Configure consul host1
  hosts: consul1
  become: yes
  become_user: root
  gather_facts: yes
  tags: [consul1]
  tasks:
    - name: Copy consul.hcl
      copy:
        src: ../configuration/consul1.hcl
        dest: /etc/consul.d/consul.hcl
    - name: Copy server.hcl
      copy:
        src: ../configuration/server.hcl
        dest: /etc/consul.d/server.hcl
    # - name: Join with other nodes
    #   ansible.builtin.shell:
    #     cmd: sudo systemctl daemon-reload
    - name: Just force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: yes
 
    - name: Make sure a service consul is enabled
      ansible.builtin.systemd:
        name: consul
        enabled: yes

    - name: Make sure a service consul is running
      ansible.builtin.systemd:
        state: started
        name: consul

- name: Configure consul host2
  hosts: consul2
  become: yes
  become_user: root
  gather_facts: yes
  tags: [consul2]
  tasks:
    - name: Copy consul2.hcl
      copy:
        src: ../configuration/consul2.hcl
        dest: /etc/consul.d/consul.hcl
    - name: Copy server.hcl
      copy:
        src: ../configuration/server.hcl
        dest: /etc/consul.d/server.hcl
    - name: Join with other nodes
      ansible.builtin.shell:
        cmd: systemctl daemon-reload
    - name: Enable Consul service
      ansible.builtin.shell:
        cmd: systemctl enable consul.service

- name: Configure consul host3
  hosts: consul3
  become: yes
  become_user: root
  gather_facts: yes
  tags: [consul3]
  tasks:
    - name: Copy consul3.hcl
      copy:
        src: ../configuration/consul3.hcl
        dest: /etc/consul.d/consul.hcl
    - name: Copy server.hcl
      copy:
        src: ../configuration/server.hcl
        dest: /etc/consul.d/server.hcl
    - name: Join with other nodes
      ansible.builtin.shell:
        cmd: systemctl daemon-reload
    - name: Enable Consul service
      ansible.builtin.shell:
        cmd: systemctl enable consul.service

- name: Configure consul host4
  hosts: consul4
  become: yes
  become_user: root
  gather_facts: yes
  tags: [consul4]
  tasks:
    - name: Copy consul4.hcl
      copy:
        src: ../configuration/consul4.hcl
        dest: /etc/consul.d/consul.hcl
    - name: Join with other nodes
      ansible.builtin.shell:
        cmd: systemctl daemon-reload
    - name: Enable Consul service
      ansible.builtin.shell:
        cmd: systemctl enable consul.service

- name: TLS
  hosts: consul1
  become: yes
  become_user: root
  gather_facts: yes
  tags: [getca]

  roles:
    - name: Get CA
      role: ansible-role-consul-tls